---    
- name: "Union HTML's"
  shell: "cat /tmp/Check_WeblogicP_{{ DATE.stdout }}.html"
  register: CheckWeblogic
  
- name: Creacion Carpeta - HTML /opt/Tomcat9/webapps/{{ id_asgard }}
  file:
      path: /opt/Tomcat9/webapps/{{ id_asgard }}
      state: directory
      mode: '0770'
  delegate_to: 172.22.16.179
  run_once: true

- name: Creacion Carpeta - HTML /opt/Tomcat9/webapps/{{ id_asgard }}
  file:
      path: /opt/Tomcat9/webapps/{{ id_asgard }}/
      state: directory
      mode: '0770'
  delegate_to: 172.22.16.179
  run_once: true

- name: "Template Weblogic HTML"
  template: 
    src: CheckState.j2.html 
    dest: /opt/Tomcat9/webapps/{{ id_asgard }}//index.html
    mode: '0777'
  delegate_to: 172.22.16.179

- name: Creacion Vista Inicial (HTML)
  template:
      src: intermediate.html.j2.html
      dest: /opt/Tomcat9/webapps/{{ id_asgard }}/intermediate.html
      mode: '777'
  run_once: true
  delegate_to: 172.22.16.179

- name: Creacion del Cierre
  template:
      src: Final.html.j2.html
      dest: /opt/Tomcat9/webapps/{{ id_asgard }}/Final.html
      mode: '777'
  delegate_to: 172.22.16.179   
  run_once: true

- name: Creacion Vista Inicial (Styles)
  template:
      src: Style.css.j2.css
      dest: /opt/Tomcat9/webapps/{{ id_asgard }}/{{ ansible_hostname }}Style.css
      mode: '777'
  delegate_to: 172.22.16.179

- name: Creacion de Botones
  template:
      src: botones.html.j2.html
      dest: /opt/Tomcat9/webapps/{{ id_asgard }}/{{ ansible_hostname }}Botones.html
      mode: '777'
  delegate_to: 172.22.16.179

- name: Creacion de Tablas
  template:
      src: tablas.j2.html
      dest: /opt/Tomcat9/webapps/{{ id_asgard }}/{{ ansible_hostname }}Tabla.html
      mode: '777'
  delegate_to: 172.22.16.179  

- name: Transferencia de Vista HTML
  shell: echo "{{ item }}" >> /opt/Tomcat9/webapps/{{ id_asgard }}/{{ ansible_hostname }}Tabla.html
  with_items:
    - "{{ CheckWeblogic.stdout_lines }}"
  delegate_to: 172.22.16.179

- name: Creacion de Primer Script
  template:
      src: ScriptBotones.js.j2.js
      dest: /opt/Tomcat9/webapps/{{ id_asgard }}/{{ ansible_hostname }}ScriptBotones.js
      mode: '777'
  delegate_to: 172.22.16.179   

- name: Creacion Vista HTML
  shell: cat /opt/Tomcat9/webapps/{{ id_asgard }}/{{ item }} >> /opt/Tomcat9/webapps/{{ id_asgard }}/index.html
  with_items:
    - "*Style.css"
    - "intermediate.html"
    - "*Botones.html"
    - "*Tabla.html"
    - "*ScriptBotones.js"
    - "Final.html"
  delegate_to: 172.22.16.179
  run_once: true

- name: "Eliminacion Archivos"
  file: 
    path: "{{ item }}"
    state: absent 
  with_items:
    - "/tmp/Check_WeblogicP_{{ DATE.stdout }}.html"
    - "/tmp/CheckState.py"

- name: Limpiando Archivos...
  file:
      path: /opt/Tomcat9/webapps/{{ id_asgard }}/{{ item }}
      state: absent
  with_items:
    - "{{ ansible_hostname }}Style.css"
    - "intermediate.html"
    - "{{ ansible_hostname }}Botones.html"
    - "{{ ansible_hostname }}Tabla.html"
    - "{{ ansible_hostname }}ScriptBotones.js"
    - "Final.html"
  delegate_to: 172.22.16.179

- debug: msg='Por Favor ingresar a la URL:http://172.22.16.179:443/{{ id_asgard }} Para poder observar la verificacion del servicio.'
  run_once: yes

- debug: msg='Creado por:Juan Jose Quintero R.'
  run_once: yes

- name: Enviar correo del Reporte
  mail:
    host: localhost
    port: 25
    subject: REPORTE WEBLOGIC CLARO
    subtype: html
    body: '
    Buenos dias
    <br>
    Adjunto reporte de Check de Sanidad de Weblogic:
    <br> 
    <br>
    <br>
    <table class="egt">
    <tr>
    <th> <img src="http://172.22.16.179:443/imagenes/LogoClaro.png" width="200" height="100" /> </th>
    <th> <h1> Area de Unix Datacenter </h1>
    </tr>
    </table>
    <br>
    <b> AVISO DE CONFIDENCIALIDAD: </b>
    <p style="color:gray;font-size: 13px;"> Este correo electrónico, incluyendo en su caso, los archivos adjuntos al mismo, pueden contener información de carácter confidencial y/o privilegiada, y se envían a la atención única y exclusivamente de la persona y/o entidad a quien va dirigido. La copia, revisión, uso, revelación y/o distribución de dicha información confidencial sin la autorización por escrito de Comunicación Celular S.A Comcel S.A está prohibida. Si usted no es el destinatario a quien se dirige el presente correo, favor de contactar al remitente respondiendo al presente correo y eliminar el correo original incluyendo sus archivos, así como cualesquiera copia del mismo. Mediante la recepción del presente correo usted reconoce y acepta que en caso de incumplimiento de su parte y/o de sus representantes a los términos antes mencionados, Comunicación Celular S.A Comcel S.A tendrá derecho a los daños y perjuicios que esto le cause. </p>

    
    <b> CONFIDENTIALITY NOTICE: </b>
    <p style="color:gray;font-size: 13px;"> This e-mail message including attachments, if any, is intended only for the person or entity to which it is addressed and may contain confidential and /or privileged material. Any review, use, disclosure or distribution of such confidential information without the written authorization of Comunicación Celular S.A Comcel S.A is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail and destroy all copies of the original message. By receiving this e-mail you acknowledge that any breach by you and/or your representatives of the above provisions may entitle Comunicación Celular S.A Comcel S.A to seek for damages. </p>
 
    '    
    from: unix@telmexla.net.co
    to:
    - William.Caicedo.Ext@claro.com.co
    - yulieth.ardilaf.ext@claro.com.co
    cc: 
    - Juan Jose Quintero Reatiga <Juan.Quinteror.Ext@claro.com.co>
    attach:
    - /opt/Tomcat9/webapps/{{ id_asgard }}/index.html
  delegate_to: 172.22.16.179
  run_once: yes  