---
- name: Obteniendo Ruta ORACLE_HOME
  shell:  "echo $ORACLE_HOME"
  register: MW_HOME
  become_user: weblogic

- name: Obteniendo Version Weblogic
  shell: cd {{ MW_HOME.stdout }}/wlserver/server/bin/; . ./setWLSEnv.sh; java weblogic.version
  register: WeblogicVersion
  become_user: weblogic

- name: Obteniendo Version de OPatch
  shell: cd {{ MW_HOME.stdout }}/OPatch;./opatch version
  register: VersionOpatch
  become_user: weblogic

- name: Obteniendo ID de Parches Instalados
  shell: cd {{ MW_HOME.stdout }}/OPatch;./opatch lspatches
  register: IDPatch
  become_user: weblogic

- name: Creando Directorios de Parche ...
  file:
    path: "{{ MW_HOME.stdout }}/OPatch/OPATCH_TOP"
    state: directory
    owner: weblogic
    group: weblogic
    mode: '0775'
  become_user: weblogic

- name: Transferencia Archivo que Contiene Parche
  fetch:
      dest: "/tmp/{{ Name_File }}"
      src: "{{ Route }}/{{ Name_File }}"
      flat: yes
  # ---- Servidor Remoto de donde trae el archivo: Suse12 y es enviado a AWX ----
  delegate_to: 172.18.91.87

- name: Copia Archivos del Parche
  copy:
    dest: "{{ MW_HOME.stdout }}/OPatch/OPATCH_TOP/{{ Name_File }}"
    src: "/tmp/{{ Name_File }}"
    owner: weblogic
    group: weblogic
    mode: '0775'


- name: Descomprimiendo Archivo .zip ...
  unarchive:
    src: "{{ MW_HOME.stdout }}/OPatch/OPATCH_TOP/{{ Name_File }}"
    dest: "{{ MW_HOME.stdout }}/OPatch/OPATCH_TOP/"
    owner: weblogic
    group: weblogic
    mode: '0775'
